Repository PLADI-ALM/PLADI-ALM-Web, pull requests merged in 2023-10, with the labels that each got.

#10 [PDW-49] feat: 예약 내역 목록 페이지 UI 및 회의실 목록 API 연결
  R
  src/App.js
  src/api/AxiosApi.js
  src/components/button/SmallButton.js
  src/components/capsule/SelectToggle.js
  src/components/rightContainer/RightContainer.js
  src/constants/BookingStatus.js
  src/constants/Path.js
  src/constants/ToggleList.js
  src/index.css
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/booking/officeBooking/OfficeInfo.js
  
Labels: 🔮 Feat

#11 [PDW-13/Feat] 자원 선택 UI 구현
  src/App.js
  src/assets/images/example.png
  src/components/card/Card.js
  src/components/resourceInfo/ResourceInfo.js
  src/components/rightContainer/RightContainer.js
  src/pages/booking/selectResource/SelectResource.js
Labels: 🔮 Feat

#12 [PDW-6] feat: 회의실 예약 화면 UI 수정 및 API 연결
  src/App.js
  src/components/card/Card.js
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingRequest.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/officeInfo/OfficeInfo.js
  src/components/searchBar/SearchBar.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeBooking/OfficeInfo.js
  src/pages/booking/selectOffice/SelectOffice.js
Labels: 🔮 Feat

#13 [PDW-50] feat: 회의실 예약 세부 조회 화면 UI 구현 및 API 연결
  src/App.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/officeBooking/SubTitleBar.js
  src/components/officeInfo/OfficeInfo.js
  src/pages/booking/officeBooking/OfficeBooking.js
Labels: 🔮 Feat

#14 [PDW-13] feat: 자원 검색 바 UI 구현
  src/components/rightContainer/RightContainer.js
  src/pages/booking/selectResource/SelectResource.js
Labels: 🔮 Feat

#15 [PDW-53] feat: 자원 예약 세부 조회 화면 UI 구현
  src/App.js
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/officeBooking/SubTitleBar.js
  src/components/resourceInfo/ResourceInfo.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: 🔮 Feat

#16 [PDW-50] feat: 회의실 예약 세부 내역 화면 API 연결
  src/components/card/Card.js
  src/pages/booking/officeBooking/OfficeBooking.js
Labels: 🔮 Feat

#17 [PDW-49] feat: 예약 내역 API 연결 및 예약 상태 태그 생성
  src/components/booking/StatusTag.js
  src/components/officeBooking/SubTitleBar.js
  src/components/searchBar/SearchBar.js
  src/constants/BookingStatus.js
  src/constants/Path.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: 🔮 Feat

#18 [PDW-53] feat: 자원 예약 세부 내역 화면 API 연결
  src/components/resourceInfo/ResourceInfo.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: 🔮 Feat

#19 [PDW-49/feat] 자원 반납 API 연결
  src/components/button/SmallButton.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
Labels: 🔮 Feat

#20 [PDW-53] fix: 자원 예약 세부 조회 화면 관련 path 및 url 수정
  src/App.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#21 [PDW-53] fix: 예약 상태 컴포넌트 수정
  src/components/officeBooking/BookingPurpose.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#22 [PDW-13] feat: 자원 검색 API 연결
  src/components/resourceInfo/ResourceInfo.js
  src/pages/booking/selectResource/SelectResource.js
Labels: 🔮 Feat

#23 [PDW-50] fix: 회의실 예약 세부 조회 화면 반응형으로 수정
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingTimeBar.js
Labels: ⛑️ Fix

#24 [PDW-50] fix: 예약 대상의 정보 조회 오류 수정
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#25 [PDW-13/FIX] 자원 검색 UI 수정 및 예외처리 구현
  src/pages/booking/selectResource/SelectResource.js
Labels: 🔮 Feat, ⛑️ Fix

#27 [PDW-56/feat] 사이드바 관리자 메뉴 및 사원정보, 로그아웃 UI 추가
  src/App.js
  src/assets/images/fullNameLogo.png
  src/assets/images/fullNameLogo.svg
  src/assets/images/sidebarIcon/archivingActive.png
  src/assets/images/sidebarIcon/archivingActive.svg
  src/assets/images/sidebarIcon/archivingInactive.png
  src/assets/images/sidebarIcon/archivingInactive.svg
  src/assets/images/sidebarIcon/bookingActive.png
  src/assets/images/sidebarIcon/bookingActive.svg
  src/assets/images/sidebarIcon/bookingInactive.png
  src/assets/images/sidebarIcon/bookingInactive.svg
  src/assets/images/sidebarIcon/bookingManageActive.svg
  src/assets/images/sidebarIcon/bookingManageInactive.svg
  src/assets/images/sidebarIcon/employeeActive.svg
  src/assets/images/sidebarIcon/employeeInactive.svg
  src/assets/images/sidebarIcon/equipmentActive.svg
  src/assets/images/sidebarIcon/equipmentInactive.svg
  src/assets/images/sidebarIcon/logout.png
  src/assets/images/sidebarIcon/logoutIcon.svg
  src/assets/images/sidebarIcon/myInfoIcon.svg
  src/assets/images/sidebarIcon/officeActive.svg
  src/assets/images/sidebarIcon/officeInactive.svg
  src/assets/images/sidebarIcon/resourceActive.png
  src/assets/images/sidebarIcon/resourceActive.svg
  src/assets/images/sidebarIcon/resourceInactive.png
  src/assets/images/sidebarIcon/resourceInactive.svg
  src/assets/images/sidebarIcon/toggleActive.png
  src/assets/images/sidebarIcon/toggleActive.svg
  src/assets/images/sidebarIcon/toggleInactive.png
  src/assets/images/sidebarIcon/toggleInactive.svg
  src/assets/images/sidebarIcon/user.png
  src/components/capsule/Capsule.js
  src/components/sidebar/MainMenu.js
  src/components/sidebar/MenuLineStyle.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/SubMenu.js
  src/constants/Path.js
Labels: 🔮 Feat

#29 [PDW-39/Feat] 관리자 검색 바 Component 생성 및 페이지 UI 구현
  src/App.js
  src/assets/images/SearchInput.svg
  src/assets/images/SearchPlus.svg
  src/components/searchBar/ManageSearchBar.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/booking/officeManage/OfficeManage.js
  src/pages/booking/officeManage/OfficeManageTableCell.js
  src/pages/booking/selectOffice/SelectOffice.js
Labels: 🔮 Feat

#31 [PDW-57/feat] build.yml 생성
  .github/workflows/build.yml
Labels: 🔮 Feat, 🎡 Infra

#32 [PDW-57] docs: build.yml 브랜치명 수정
  .github/workflows/build.yml
Labels: 📒 Docs, ⛑️ Fix

#33 [PDW-57] docs: build.yml 수정
  .github/workflows/build.yml
Labels: ⛑️ Fix

#34 [PDW-57] fix: build.yml 수정 및 오류 수정
  .github/workflows/build.yml
  src/App.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/sidebar/Sidebar.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeManage/OfficeManage.js
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/selectOffice/SelectOffice.js
  src/pages/booking/selectResource/SelectResource.js
  src/pages/main/MainPage.js
  src/pages/user/Login.js
Labels: ⛑️ Fix

#36 [PDW-14] feat: 자원 예약 화면 내 달력 컴포넌트 추가
  package-lock.json
  package.json
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/resourceBooking/CustomCalendar.css
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: 🔮 Feat

#37 [PDW-57/docs] 사이트 설명 변경
  public/index.html
Labels: 📒 Docs

#40 [PDW-14] feat: 자원 예약 화면 API 연결
  src/App.js
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/resourceBooking/CustomCalendar.css
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
Labels: 🔮 Feat

#39 [PDW-54/Feat] 자원 예약 내역 UI 구현
  src/App.js
  src/pages/manager/officeManage/OfficeManage.js
  src/pages/manager/officeManage/OfficeManageTableCell.js
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/manager/resourceBookingManage/ResourceBookingManageCell.js
  src/pages/manager/resourceManage/ResourceManage.js
Labels: 🔮 Feat

#42 [PDW-55] feat: 관리자 회의실 예약 세부 조회 화면 API 연결
  src/App.js
  src/api/AxiosApi.js
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeBooking/OfficeBookingCheck.js
Labels: 🔮 Feat

#41 [PDW-28/feat] 로그인 API 연결 및 사이드바 로그인 유무 확인 추가
  package-lock.json
  package.json
  src/components/sidebar/Sidebar.js
  src/index.js
  src/pages/user/Login.js
  src/utils/CookiesUtil.js
  src/utils/IsLoginUtil.js
Labels: 🔮 Feat

#43 [PDW-56/feat] 사이드바 회원정보 연동 및 관리자 여부에 따른 메뉴 변동 적용
  src/components/sidebar/Sidebar.js
  src/pages/user/Login.js
  src/utils/IsLoginUtil.js
Labels: 🔮 Feat

#44 [PDW-56/fix] 경로오류 수정
  src/App.js
Labels: 🪧 HOTFIX

#46 [PDW-54/fix] 자원 예약 내역 map 수정
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
Labels: 🔮 Feat

#48 [PDW-57] fix: build.yml echo >> 대신 >로 변경
  .github/workflows/build.yml
  public/index.html
Labels: ⛑️ Fix

#49 [PDW-57] fix: build.yml echo > 대신 >>로 변경
  .github/workflows/build.yml
Labels: ⛑️ Fix

#50 [PDW-57] fix: build.yml touch .env 삭제
  .github/workflows/build.yml
Labels: ⛑️ Fix

#51 [PDW-57] fix: build.yml 수정
  .github/workflows/build.yml
  src/pages/user/Login.js
Labels: ⛑️ Fix

#52 [PDW-42] 관리자 자원 예약 세부 조회 API 연결
  src/App.js
  src/components/officeBooking/BookingPurpose.js
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
Labels: 🔮 Feat

#47 [PDW-54/feat] 자원 예약 허가 및 반려 API 연결
  src/api/AxiosApi.js
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/manager/resourceBookingManage/ResourceBookingManageCell.js
Labels: 🔮 Feat

#53 [PDW-29/fix] Axios URL 및 사용법 수정
  src/api/AxiosApi.js
  src/components/sidebar/Sidebar.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeBooking/OfficeBookingCheck.js
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
  src/pages/booking/selectOffice/SelectOffice.js
  src/pages/booking/selectResource/SelectResource.js
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/user/Login.js
Labels: ⛑️ Fix

#54 [PDW-42] 관리자 자원 예약 세부 조회 토큰 적용
  src/App.js
  src/pages/booking/officeBooking/OfficeBookingCheck.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
Labels: 🔮 Feat

#55 [PDW-39/Feat] 회의실 예약내역 UI 및 API 구현
  src/App.js
  src/assets/images/RangeArrow.svg
  src/pages/manager/officeBookingManage/OfficeBookingManage.js
  src/pages/manager/officeBookingManage/OfficeBookingManageCell.js
Labels: 🔮 Feat

#56 [PDW-39/Feat] 회의실 예약 내역 상세 보기 연결
  src/pages/manager/officeBookingManage/OfficeBookingManageCell.js
Labels: 🔮 Feat

#57 [PDW-29/feat] 로그아웃 API 연결
  src/components/sidebar/Sidebar.js
  src/pages/booking/bookedList/BookedList.js
Labels: 🔮 Feat

#58 [PDW-54/Feat] 자원 예약 반납 api 연결 및 상세보기 연결
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/manager/resourceBookingManage/ResourceBookingManageCell.js
Labels: 🔮 Feat

#62 [PDW-54/Fix] api 헤더 부분 연결 수정 및 직급 추가로 인한 요청자 표시 코드 수정
  src/pages/manager/officeBookingManage/OfficeBookingManage.js
  src/pages/manager/officeBookingManage/OfficeBookingManageCell.js
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/manager/resourceBookingManage/ResourceBookingManageCell.js
Labels: ⛑️ Fix

#61 [PDW-5/Fix] 시작 시간 설정 안되는 오류 수정
  src/pages/booking/selectOffice/SelectOffice.js
Labels: ⛑️ Fix

#63 [PDW-54/Fix] 자원 예약 상세보기 수정 및 Link 코드 삭제
  src/components/resourceInfo/ResourceInfo.js
  src/pages/booking/selectResource/SelectResource.js
  src/pages/manager/officeBookingManage/OfficeBookingManageCell.js
  src/pages/manager/resourceBookingManage/ResourceBookingManageCell.js
Labels: ⛑️ Fix

#64 [PDW-29/feat] 토큰 에러 처리 및 에러 처리 메소드 생성
  src/components/sidebar/Sidebar.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/user/Login.js
  src/utils/ErrorHandlerUtil.js
Labels: 🔮 Feat

#65 [PDW-14] fix: 자원 예약 화면 내 WhiteContainer로 수정
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#67 [PDW-14] fix: 네트워크 오류 처리 수정
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#69 [PDW-42] fix: 네트워크 예외 처리 수정
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeBooking/OfficeBookingCheck.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
Labels: ⛑️ Fix

#70 [PDW-36/feat] 자원 관리 페이지 UI 구현
  src/App.js
  src/components/searchBar/ManageSearchBar.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: 🔮 Feat

#71 [PDW-44/feat] 직원 계정 목록 조회 및 검색
  src/App.js
  src/api/AxiosApi.js
  src/components/capsule/RoleCapsule.js
  src/components/searchBar/ManageSearchBar.js
  src/constants/Path.js
  src/pages/manager/userManage/UserManage.js
  src/pages/manager/userManage/UserManageLine.js
  src/utils/ErrorHandlerUtil.js
Labels: 🔮 Feat

#72 [PDW-36/feat] 자원 관리 페이지 검색 api 연결
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: 🔮 Feat

#73 [PDW-45/feat] 신규 직원 등록 모달 UI
  src/assets/images/arrowDown.svg
  src/assets/images/moreIcon.png
  src/assets/images/moreIcon.svg
  src/components/capsule/SelectToggle.js
  src/components/modal/Modal.js
  src/components/searchBar/ManageSearchBar.js
  src/components/searchBar/SearchBar.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/manager/userManage/UserManage.js
  src/pages/manager/userManage/UserManageLine.js
  src/pages/manager/userManage/UserModal.js
Labels: 🔮 Feat

#74 [PDW-37/feat] 자원 추가 UI 구현
  src/App.js
  src/assets/images/AddImage.png
  src/components/searchBar/ManageSearchBar.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: 🔮 Feat

#75 [PDW-37/feat] 이미지 추가 후 삭제 버튼 구현
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: 🔮 Feat

#77 [PDW-6] fix: 타임바 포함 관련 수정사항 처리
  src/components/officeBooking/BookingPurpose.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/officeBooking/SubTitleBar.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/officeBooking/OfficeBookingCheck.js
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
Labels: ⛑️ Fix

#76 [PDW-45/feat] 신규 직원 등록 모달 권한 및 등록 버튼 UI
  src/components/button/BigSquareButton.js
  src/components/capsule/RoleCapsule.js
  src/components/modal/Modal.js
  src/pages/manager/userManage/UserManageLine.js
  src/pages/manager/userManage/UserModal.js
Labels: 🔮 Feat

#79 [PDW-29/fix] 토큰 에러시 로그아웃 처리 재설정
  .gitignore
  src/utils/ErrorHandlerUtil.js
  src/utils/IsLoginUtil.js
Labels: ⛑️ Fix

#78 [PDW-41/feat] 자원 관리 세부 조회 화면 UI 구성
  src/App.js
  src/pages/manager/resourceManage/ResourceManageDetail.js
Labels: 🔮 Feat

#80 [PDW-6/fix] 회의실 예약 화면 내 오류 수정
  src/components/officeBooking/BookingTimeBar.js
  src/components/officeInfo/OfficeInfo.js
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#81 [PDW-6/fix] 회의실 예약 화면 내 오류 수정
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/officeBooking/OfficeBooking.js
Labels: ⛑️ Fix

#82 [PDW-6] fix: 회의실 예약 내 오류 수정
  src/components/officeBooking/BookingTimeBar.js
  src/pages/booking/officeBooking/OfficeBooking.js
Labels: ⛑️ Fix

#83 [PDW-5/fix] 회의실 사진 연결 및 검색 바 변경
  src/components/capsule/SelectToggle.js
  src/pages/booking/selectOffice/SelectOffice.js
  src/pages/booking/selectResource/SelectResource.js
Labels: ⛑️ Fix

#84 [PDW-37/feat] gitignore 설정 및 이미지 추가 url연결
  .gitignore
  src/api/AxiosApi.js
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: 🔮 Feat

#87 [PDW-41/feat] 자원별 대여 이력 조회 API 연결 및 더보기 버튼 추가
  src/App.js
  src/assets/images/button/triple_dot_icon.svg
  src/pages/manager/resourceManage/ResourceManageDetail.js
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: 🔮 Feat

#89 [PDW-6] fix: 자원 예약 화면 내 이미 예약된 날짜 미포함되도록 수정
  src/pages/booking/officeBooking/OfficeBooking.js
  src/pages/booking/resourceBooking/ResourceBooking.js
Labels: ⛑️ Fix

#90 [PDW-6] fix: 회의실 예약 내 get 요청 실패할 경우 뒤로가기 추가
  src/pages/booking/officeBooking/OfficeBooking.js
Labels: ⛑️ Fix

#92 [PDW-6] fix: 회의실 예약 내 날짜 변경 시 관련 변수 초기화 추가
  src/components/officeBooking/BookingTimeBar.js
Labels: ⛑️ Fix

#93 [PDW-37/fix] 자원 예약관리 설정 버튼 ui 변경
  src/pages/manager/officeBookingManage/OfficeBookingManageCell.js
Labels: ⛑️ Fix

#95 [PDW-37/feat] 자원 등록 api 연결
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: 🔮 Feat

#97 [PDW-61/fix] 자원 관리 목록 UI 변경
  src/components/searchBar/ManageSearchBar.js
  src/components/toggle/Toggle.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: ⛑️ Fix

#98 [PDW-63/fix] 기획 변경으로 인한 사이드바 및 path 변경
  src/App.js
  src/assets/images/sidebarIcon/AdminActive.svg
  src/assets/images/sidebarIcon/AdminInactive.svg
  src/assets/images/sidebarIcon/ArchivingActive.svg
  src/assets/images/sidebarIcon/ArchivingInactive.svg
  src/assets/images/sidebarIcon/BookingActive.svg
  src/assets/images/sidebarIcon/BookingInactive.svg
  src/assets/images/sidebarIcon/EquipmentActive.svg
  src/assets/images/sidebarIcon/EquipmentInactive.svg
  src/assets/images/sidebarIcon/LogoutIcon.svg
  src/assets/images/sidebarIcon/MyBookingActive.svg
  src/assets/images/sidebarIcon/MyBookingInactive.svg
  src/assets/images/sidebarIcon/MyInfoIcon.svg
  src/assets/images/sidebarIcon/ToggleActive.svg
  src/assets/images/sidebarIcon/ToggleInactive.svg
  src/assets/images/sidebarIcon/officeActive.svg
  src/assets/images/sidebarIcon/officeInactive.svg
  src/assets/images/sidebarIcon/resourceActive.svg
  src/assets/images/sidebarIcon/resourceInactive.svg
  src/components/sidebar/MainMenu.js
  src/components/sidebar/MenuLineStyle.js
  src/components/sidebar/Sidebar.js
  src/constants/Path.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
Labels: ⛑️ Fix

#99 [PDW-58/hotfix] 회의실 및 자원 목록 조회 header 값 추가
  src/pages/booking/selectOffice/SelectOffice.js
  src/pages/booking/selectResource/SelectResource.js
Labels: 🪧 HOTFIX

#100 [PDW-40/Fix] 예약자 직급을 전화번호로 변경
  src/pages/manager/officeManage/OfficeBookingManageDetail.js
Labels: ⛑️ Fix

#101 [PDW-61/fix] 관리자 장비 목록 API 연결
  src/App.js
  src/components/toggle/Toggle.js
  src/constants/Path.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: ⛑️ Fix

#103 [PDW-42/fix] 관리자 장비 예약 개별 조회 화면 수정
  src/pages/manager/resourceManage/ResourceManageDetail.js
Labels: ⛑️ Fix

#104 [PDW-62/feat] 관리자 장비 활성/비활성 API 연결
  src/pages/manager/resourceManage/ResourceManageTableCell.js
Labels: 🔮 Feat

#105 [PDW-40] feat: 회의실 목록 API 연결
  src/pages/manager/officeManage/OfficeManage.js
Labels: 🔮 Feat

#106 [PDW-58/fix] 자원 추가 2차 gui에 맞게 수정
  src/assets/images/AddImage.png
  src/assets/images/AddImage.svg
  src/pages/manager/resourceManage/ResourceManageAdd.js
  src/pages/manager/resourceManage/ResourceManageDetail.js
Labels: ⛑️ Fix

#108 [PDW-58/feat] 자원수정 api 연결
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: ⛑️ Fix

#109 [PDW-67/rename] 자원 -> 장비 네이밍 변경
  .github/CODEOWNERS
  src/components/card/Card.js
  src/components/resourceInfo/ResourceInfo.js
  src/constants/ToggleList.js
  src/pages/booking/bookedList/BookedLine.js
  src/pages/booking/bookedList/BookedList.js
  src/pages/booking/resourceBooking/ResourceBooking.js
  src/pages/booking/resourceBooking/ResourceBookingCheck.js
  src/pages/booking/selectResource/SelectResource.js
  src/pages/manager/resourceBookingManage/ResourceBookingManage.js
  src/pages/manager/resourceManage/ResourceManageAdd.js
  src/pages/manager/resourceManage/ResourceManageDetail.js
Labels: 🧵 Refactor

#110 [PDW-65] refactor: 직원 관리 목록 컬럼 변경
  src/pages/manager/userManage/UserManage.js
  src/pages/manager/userManage/UserManageLine.js
Labels: ⛑️ Fix

#111 [PDW-65/fix] 빈 직원 목록 처리
  src/pages/booking/bookedList/BookedList.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/userManage/UserManage.js
Labels: ⛑️ Fix

#112 [PDW-58/fix] 자원 추가 안되는 오류 수정
  src/pages/manager/resourceManage/ResourceManageAdd.js
Labels: ⛑️ Fix

#113 [PDW-45/feat] 직원 등록
  src/components/button/BigSquareButton.js
  src/components/capsule/RoleCapsule.js
  src/components/capsule/SelectToggle.js
  src/components/modal/Modal.js
  src/pages/manager/userManage/UserModal.js
Labels: 🔮 Feat

#114 [PDW-60/feat] 직원 정보 수정
  src/components/modal/BigModal.js
  src/components/modal/Modal.js
  src/components/modal/MoreModal.js
  src/pages/manager/resourceManage/ResourceManageAdd.js
  src/pages/manager/userManage/UserManage.js
  src/pages/manager/userManage/UserManageLine.js
  src/pages/manager/userManage/UserModal.js
  src/pages/manager/userManage/UserMoreModal.js
Labels: 🔮 Feat

#115 [PDW-46/feat] 직원 탈퇴 API 연결
  src/pages/manager/userManage/UserMoreModal.js
Labels: 🔮 Feat

#116 [PDW-66/feat] 회의실 활성/비활성 API 연결
  src/pages/manager/officeManage/OfficeManage.js
  src/pages/manager/officeManage/OfficeManageTableCell.js
Labels: 🔮 Feat

#117 [PDW-65/feat] 관리자 부서별 직원 검색 추가
  src/components/searchBar/ManageSearchBar.js
  src/pages/manager/officeManage/OfficeManage.js
  src/pages/manager/resourceManage/ResourceManage.js
  src/pages/manager/userManage/UserManage.js
Labels: 🔮 Feat
