Repository PLADI-ALM/PLADI-ALM-Web, pull requests merged in 2023-11, with the labels that each got.

#118 [PDW-66/feat] 관리자 회의실 목록 조회 API 연결
  src/pages/booking/selectOffice/SelectOffice.js
  src/pages/manager/officeManage/OfficeManage.js
Labels: 🔮 Feat

#120 [PDW-71/refactor] 장비 책임자, 보관장소 추가
  src/components/capsule/Capsule.js
  src/components/card/Card.js
  src/components/card/OfficeInfo.js
  src/components/card/ResourceDetailInfo.js
  src/components/card/ResourceInfo.js
  src/pages/admin/office/OfficeBookingManageDetail.js
  src/pages/admin/resource/ResourceManageDetail.js
  src/pages/basic/booking/office/OfficeBooking.js
  src/pages/basic/booking/office/OfficeBookingCheck.js
  src/pages/basic/booking/office/SelectOffice.js
  src/pages/basic/booking/resource/ResourceBooking.js
  src/pages/basic/booking/resource/ResourceBookingCheck.js
  src/pages/basic/booking/resource/SelectResource.js
Labels: 🧵 Refactor

#121 [PDW-69/refactor] 일반 사원 예약 반납 기능 제거
  src/App.js
  src/components/sidebar/MenuLineStyle.js
  src/constants/Path.js
  src/pages/basic/myBookings/BookedLine.js
  src/pages/basic/myBookings/BookedList.js
Labels: 🧵 Refactor

#122 [PDW-68/fix] 직원 추가 시 부서 목록 호출 문제 해결
  src/App.js
  src/pages/admin/user/UserModal.js
Labels: ⛑️ Fix

#123 [PDW-70/refactor] 장비 목록 검색바 UI 수정
  src/App.js
  src/assets/images/Search.svg
  src/assets/images/SelectArrow.svg
  src/assets/images/search.png
  src/components/button/ImageFullButton.js
  src/components/button/ImagePaddingButton.js
  src/components/capsule/DropBox.js
  src/components/capsule/SelectToggle.js
  src/components/rightContainer/RightContainer.js
  src/components/searchBar/ManageSearchBar.js
  src/components/searchBar/SearchBar.js
  src/index.css
  src/pages/admin/user/UserModal.js
  src/pages/basic/booking/office/SelectOffice.js
  src/pages/basic/booking/resource/SelectResource.js
Labels: 🧵 Refactor

#124 [PDW-73/fix] 예약 내역 관리 컬럼 수정
  src/components/searchBar/ManageSearchBar.js
  src/pages/admin/officeBookings/OfficeBookingManage.js
  src/pages/admin/officeBookings/OfficeBookingManageCell.js
  src/pages/admin/resource/ResourceManageAdd.js
  src/pages/admin/resourceBookings/ResourceBookingManage.js
  src/pages/admin/resourceBookings/ResourceBookingManageCell.js
Labels: ⛑️ Fix

#125 [PDW-70/fix] 장비 목록 검색 API 연결
  src/components/searchBar/ManageSearchBar.js
  src/pages/basic/booking/office/SelectOffice.js
  src/pages/basic/booking/resource/SelectResource.js
Labels: ⛑️ Fix

#126 [PDW-74/fix] 직원 관리 더보기 버튼 위치 조정
  src/components/modal/MoreModal.js
  src/pages/basic/myBookings/BookedList.js
Labels: ⛑️ Fix

#129 [PDW-67/fix] 회의실 예약 목적 마진 수정
  .github/workflows/build.yml
  src/components/officeBooking/BookingPurpose.js
Labels: ⛑️ Fix

#133 [PDW-87/fix] 직원 목록 조회(총 인원수, 소속, 소속 필터링) 추가
  src/components/capsule/DropBox.js
  src/components/searchBar/ManageSearchBar.js
  src/constants/ToggleList.js
  src/pages/admin/user/UserManage.js
  src/pages/admin/user/UserManageLine.js
Labels: ⛑️ Fix

#134 [PDW-87/fix] 직원 등록/수정 시 보유자산, 소속 데이터 추가
  src/components/capsule/DropBox.js
  src/components/modal/BigModal.js
  src/components/searchBar/ManageSearchBar.js
  src/pages/admin/user/UserModal.js
Labels: ⛑️ Fix

#135 [PDW-86/fix] 차량, 장비 '제조사' 데이터 추가
  src/components/card/ResourceInfo.js
  src/pages/admin/car/CarManage.js
  src/pages/admin/resource/ResourceManage.js
  src/pages/basic/booking/car/CarBooking.js
  src/pages/basic/booking/car/CarBookingCheck.js
  src/pages/basic/booking/car/SelectCar.js
  src/pages/basic/booking/resource/ResourceBooking.js
  src/pages/basic/booking/resource/ResourceBookingCheck.js
  src/pages/basic/booking/resource/SelectResource.js
Labels: ⛑️ Fix

#136 [PDW-77/fix] 관리자 차량/장비 목록 id 변경
  src/pages/admin/car/CarManage.js
  src/pages/admin/resource/ResourceManage.js
Labels: 🔮 Feat

#137 [PDW-90/feat] 내 정보 수정
  src/components/capsule/DropBox.js
  src/components/modal/BigModal.js
  src/components/modal/UserModal.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/sidebar/Sidebar.js
  src/pages/admin/user/UserManage.js
  src/pages/admin/user/UserMoreModal.js
Labels: 🔮 Feat

#138 [PDW-93/feat] 관리자 차량/장비 반납 모달 추가
  src/components/capsule/DropBox.js
  src/components/modal/BigModal.js
  src/components/modal/CarReturnModal.js
  src/components/modal/ResourceReturnModal.js
  src/components/modal/UserModal.js
  src/pages/admin/carBookings/CarBookingManageCell.js
  src/pages/admin/resourceBookings/ResourceBookingManageCell.js
Labels: 🔮 Feat

#139 [PDW-92/fix] 예약자가 직접 차량/장비 반납 가능
  src/components/modal/CarReturnModal.js
  src/components/modal/ResourceReturnModal.js
  src/constants/Path.js
  src/pages/admin/carBookings/CarBookingManageCell.js
  src/pages/admin/resourceBookings/ResourceBookingManageCell.js
  src/pages/basic/myBookings/BookedLine.js
Labels: ⛑️ Fix

#140 [PDW-75/feat] 자원 예약
  src/components/modal/BookingInfoModal.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/resourceBooking/TimeSelector.js
  src/constants/Path.js
  src/constants/ToggleList.js
  src/index.css
  src/pages/admin/carBookings/CarBookingManage.js
  src/pages/basic/booking/resource/CustomCalendar.css
  src/pages/basic/booking/resource/ResourceBooking.js
Labels: 🔮 Feat

#141 [PDW-87/feat] 직원 관리 목록 부여자산 반영
  src/pages/admin/user/UserManage.js
Labels: 🔮 Feat

#142 [PDW-94/feat] 장비 추가 및 수정
  src/assets/images/EmptyImg.svg
  src/components/rightContainer/RightContainer.js
  src/pages/admin/car/CarManageAdd.js
  src/pages/admin/resource/ResourceManageAdd.js
  src/pages/admin/resource/ResourceManageDetail.js
Labels: 🔮 Feat, ⛑️ Fix

#143 [PDW-94/feat] 차량 추가/수정
  src/App.js
  src/pages/admin/car/CarManageAdd.js
Labels: 🔮 Feat

#144 [PDW-96/feat] 관리자 차량 상세 조회 및 삭제
  src/App.js
  src/constants/Path.js
  src/pages/admin/car/CarManage.js
  src/pages/admin/car/CarManageAdd.js
  src/pages/admin/car/CarManageDetail.js
  src/pages/admin/resource/ResourceManageDetail.js
Labels: 🔮 Feat

#145 [PDW-94/fix] 차량/장비 수정 시 사진 처리
  src/pages/admin/car/CarManageAdd.js
  src/pages/admin/resource/ResourceManageAdd.js
Labels: ⛑️ Fix

#146 [PDW-75/feat] 장비 예약 정보 확인
  src/components/modal/BookingInfoModal.js
  src/components/officeBooking/BookingTimeBar.js
  src/components/resourceBooking/TimeSelector.js
  src/constants/ToggleList.js
  src/pages/admin/car/CarManageAdd.js
  src/pages/admin/resource/ResourceManageAdd.js
  src/pages/basic/booking/resource/ResourceBooking.js
  src/pages/basic/user/Login.js
  src/utils/ErrorHandlerUtil.js
  src/utils/ImageUtil.js
Labels: 🔮 Feat

#148 [PDW-98/feat] 비밀번호 재설정 - 인증코드 전송 화면
  src/App.js
  src/pages/basic/user/Login.js
  src/pages/basic/user/ResetPassword.js
Labels: 🔮 Feat

#149 [PDW-75/feat] 장비 예약 시간별 예약 정보 확인
  src/components/modal/BookingInfoModal.js
  src/components/resourceBooking/TimeSelector.js
  src/pages/admin/car/CarManageTableCell.js
  src/pages/basic/booking/resource/ResourceBooking.js
Labels: 🔮 Feat

#150 [PDW-98/feat] 비밀번호 재설정
  src/App.js
  src/pages/basic/user/EmailCheck.js
  src/pages/basic/user/Login.js
  src/pages/basic/user/ResetPassword.js
Labels: 🔮 Feat

#151 [PDW-32/fix] 회의실, 장비, 차량 추가 오류 수정
  src/components/sidebar/Sidebar.js
  src/constants/Path.js
  src/pages/admin/car/CarManageAdd.js
  src/pages/admin/office/OfficeManageAdd.js
  src/pages/admin/resource/ResourceManageAdd.js
  src/pages/basic/user/Login.js
Labels: ⛑️ Fix
